<?php 
    $this->plugin('basePath')->setBasePath('/public/'); 
    $this->headLink()->prependStylesheet($this->basePath('css/index.css')) ;
?>

<style>
    .abd-menu-icon i { padding: 0 20px; }
    .intro .slogan {padding: 100px 60px;}
</style>

<div class="container">
    <ul id="gn-menu" class="gn-menu-main">
        <li class="gn-trigger">
            <a class="gn-icon gn-icon-menu"><span>Menu</span></a>
            <nav class="gn-menu-wrapper">
                <div class="gn-scroller">
                    <ul class="gn-menu">
<!--                        <li class="gn-search-item">
                            <input placeholder="Search" type="search" class="gn-search">
                            <a class="gn-icon gn-icon-search"><span>Search</span></a>
                        </li>-->
<!--                        <li> <a href="#about" class="abd-menu-icon"><i class="fa fa-heart"></i> Inteligência Emocional</a></li>-->
                        <li> <a href="#curso-ie" class="abd-menu-icon"><i class="fa fa-heart"></i> Inteligência Emocional</a></li>
                        <li><a href="#workshop-ap" class="abd-menu-icon"><i class="fa fa-line-chart"></i> Alta Performance</a></li>
                        <!--<li><a href="#works" class="gn-icon gn-icon-help">Works</a></li>-->
<!--                        <li> <a href="#contact" class="gn-icon gn-icon-archive">Contact</a> </li>-->
                    </ul>
                </div><!-- /gn-scroller -->
            </nav>
        </li>
        <li>
            <a href="/">Abundância Coaching</a>
        </li>
        <li class="hidden-xs">
            <ul class="company-social">
                <li class="social-facebook"><a href="https://www.facebook.com/abundanciacoachingoficial" target="_blank"><i class="fa fa-facebook"></i></a></li>
                <li class="social-instagram"><a href="https://www.instagram.com/abundanciacoachingoficial/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                <!--<li class="social-twitter"><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>-->
                <!--<li class="social-dribble"><a href="#" target="_blank"><i class="fa fa-dribbble"></i></a></li>-->
                <!--<li class="social-google"><a href="#" target="_blank"><i class="fa fa-google-plus"></i></a></li>-->
            </ul>	
        </li>
    </ul>
</div>

<!-- Section: intro -->
<section id="intro" class="intro" style="background-image: url(<?= $this->basePath('img/idvisual/abundancia.png') ?>)">
    <div class="slogan">
        <!--<h1>Abundância Coaching</h1>-->
        <img src="<?= $this->basePath('img/idvisual/logo_500.png') ?>" />
        <p style="font-size: 25px; font-weight: bolder">Sua vida pode ser mais que pagar contas...</p>
    </div>	
</section>
<!-- /Section: intro -->

<!-- Section: about -->
<section id="curso-ie" class="home-section text-center bg-gray">
    <div class="heading-curso-ie">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="section-heading">
                        <h2>Inteligência Emocional com Coaching</h2>
                        <p>Aprenda a gerenciar suas emoções para o sucesso, tenha domínio sobre seus comportamentos, conquiste!</p>
                        <p><button type="button" class="btn btn-default" target="_blank">Inscrições encerradas</button></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 float-none">
        <div class="row">
            <img src="<?= $this->basePath('img/index/ie-banner.png') ?>" style="width: 100%"/>
        </div>		
    </div>
</section>
<!-- /Section: about -->

<!-- Section: works -->
<section id="workshop-ap" class="home-section text-center bg-gray">
    <div class="heading-workshop-ap">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="section-heading">
                        <h2>Alta Performance <br> <i style="font-size: smaller">Coaching lifestyle</i></h2>
                        <p>Faça mais, em menos tempo, preservando seus relacionamentos e alcance lugares altos, muito altos.</p>
                        <p><a class="btn btn-primary" href="https://www.sympla.com.br/alta-performance---coaching-lifestyle__170295" target="_blank">Faça sua inscrição AGORA aqui</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-12 float-none">
        <div class="row">
            <img src="<?= $this->basePath('img/index/workshop-ap.png') ?>" />
        </div>
    </div>
</section>
<!-- /Section: works -->

<!-- Section: contact -->
<!--<section id="contact" class="home-section text-center">
    <div class="heading-contact marginbot-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">

                    <div class="section-heading">
                        <h2>Get in touch</h2>
                        <p>Lorem ipsum dolor sit amet, no nisl mentitum recusabo per, vim at blandit qualisque dissentiunt. Diam efficiantur conclusionemque ut has</p>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="container">

        <div class="row">
            

        </div>	

    </div>
</section>-->
<!-- /Section: contact -->

<footer>
    <div class="col-md-12 col-lg-12">
        
    </div>
</footer>
